#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         3
bspc config window_gap          20

bspc config left_padding 30
bspc config right_padding 30
bspc config bottom_padding 30

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a kitty desktop='^1'
bspc rule -a discord desktop='^6'
bspc rule -a gl state=borderless_monocle
bspc rule -a Spotify desktop='^7'

bsp-layout set tall I
bsp-layout set tall II
bsp-layout set tall III
bsp-layout set tall IV
bsp-layout set tall V
bsp-layout set tall VI
bsp-layout set tall VII

# Border
bspc config focused_border_color        "#9399b2"
bspc config normal_border_color         "#9399b2"
bspc config active_border_color         "#9399b2"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom --experimental-backend &
# Network Applet
nm-applet --indicator &
# Kill firewall-applet
killall -9 firewall-applet &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

# Blueman-applet
blueman-applet &

# Emacs daemon
emacs --daemon &

# Spotifyd --no-daemon
spotifyd --config-path .config/spotifyd/spotifyd.conf &

# Start ntfd
ntfd &

# Fixes the dumb fuck issue of not being able to move my trackpad 
# while typing or gaming
xinput set-prop 12 325 0
